"""Add status to saved_designs

Revision ID: 645da3c25fbb
Revises: a402bbf0d0a1
Create Date: 2026-07-20 12:30:06.148244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645da3c25fbb'
down_revision: Union[str, Sequence[str], None] = 'a402bbf0d0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_designs', sa.Column('status', sa.String(), nullable=False))
    op.create_index(op.f('ix_saved_designs_status'), 'saved_designs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_designs_status'), table_name='saved_designs')
    op.drop_column('saved_designs', 'status')
    # ### end Alembic commands ###
